# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

page.title: HomeCooked.nl
site.url: www.homecooked.nl

highlighter: rouge
paginate: 10 # pagination based on number of posts
paginate_path: "{{site.url}}/page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : http://BasLangenberg.github.io

# Fix encoding
encoding: utf-8

permalink: /post/:title
exclude: ['Gemfile','Gemfile.lock','Rakefile','.git']
paginate: 10
